ZCityDarkRPShop = ZCityDarkRPShop or {}

AddCSLuaFile("zcity_darkrp_npc_shop/sh_config.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/sh_camera_system.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_menu.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_jobs_money.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_spawn_system.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_safezone_system.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_housing_system.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_admin_hub.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_backpack_system.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_camera_system.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_corpse_loot.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_scoreboard.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_darkrp_hud.lua")
AddCSLuaFile("zcity_darkrp_npc_shop/cl_simplerr_hide.lua")

include("zcity_darkrp_npc_shop/sh_config.lua")
include("zcity_darkrp_npc_shop/sh_camera_system.lua")

if SERVER then
    include("zcity_darkrp_npc_shop/sv_storage.lua")
    include("zcity_darkrp_npc_shop/sv_core.lua")
    include("zcity_darkrp_npc_shop/sv_net.lua")
    include("zcity_darkrp_npc_shop/sv_jobs_money.lua")
    include("zcity_darkrp_npc_shop/sv_ulx.lua")
    include("zcity_darkrp_npc_shop/sv_spawn_system.lua")
    include("zcity_darkrp_npc_shop/sv_safezone_system.lua")
    include("zcity_darkrp_npc_shop/sv_housing_system.lua")
    include("zcity_darkrp_npc_shop/sv_backpack_system.lua")
    include("zcity_darkrp_npc_shop/sv_camera_system.lua")
    include("zcity_darkrp_npc_shop/sv_corpse_loot.lua")
    include("zcity_darkrp_npc_shop/sv_simplerr_hide.lua")

    hook.Add("Initialize", "ZCityDarkRPShop.Initialize", function()
        ZCityDarkRPShop.Storage.Initialize()
        ZCityDarkRPShop.Core.LoadCatalog()
        ZCityDarkRPShop.Core.LoadSettings()
        ZCityDarkRPShop.Core.LoadNPCs()
        ZCityDarkRPShop.JobRuntime.LoadJobsData()
        ZCityDarkRPShop.SpawnSystem.Load()
        ZCityDarkRPShop.SafeZones.Load()
        ZCityDarkRPShop.Housing.Load()
        ZCityDarkRPShop.Core.GetDetectedCatalog(true)
    end)

    hook.Add("InitPostEntity", "ZCityDarkRPShop.SpawnSavedNPCs", function()
        ZCityDarkRPShop.Core.RespawnNPCs()
    end)
else
    include("zcity_darkrp_npc_shop/cl_menu.lua")
    include("zcity_darkrp_npc_shop/cl_jobs_money.lua")
    include("zcity_darkrp_npc_shop/cl_spawn_system.lua")
    include("zcity_darkrp_npc_shop/cl_safezone_system.lua")
    include("zcity_darkrp_npc_shop/cl_housing_system.lua")
    include("zcity_darkrp_npc_shop/cl_admin_hub.lua")
    include("zcity_darkrp_npc_shop/cl_backpack_system.lua")
    include("zcity_darkrp_npc_shop/cl_camera_system.lua")
    include("zcity_darkrp_npc_shop/cl_corpse_loot.lua")
    include("zcity_darkrp_npc_shop/cl_scoreboard.lua")
    include("zcity_darkrp_npc_shop/cl_darkrp_hud.lua")
    include("zcity_darkrp_npc_shop/cl_simplerr_hide.lua")
end
